import { useCallback, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import logo from "../../public/logo-abertura.svg";
import NavigationModal from "@components/compound/NavigationModal";
import Map from "@components/simple/Map";
import { Box, Fade } from "@mui/material";
import DataProcessingForm from "@components/compound/DataProcessingForm";
import { useAuth } from '@src/services/auth/authContext.js';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export interface Area {
  upperRight: { latitude: number; longitude: number };
  lowerLeft: { latitude: number; longitude: number };
}

export default function Home() {
  const [area, setArea] = useState<Area>({
    upperRight: { latitude: 0, longitude: 0 },
    lowerLeft: { latitude: 0, longitude: 0 },
  });

  
  const { isAuthenticated } = useAuth();
  const router = useRouter();
  
  useEffect(() => {
    if (!isAuthenticated) {
      router.push('/');  
    }
  }, [isAuthenticated, router]);
  

  const onPolygonClick = useCallback((area: Area) => {
    setArea(area);
  }, []);

  return (
    <>
      <Head>
        <title>SAPS | Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationModal />

      <main className={roboto.className}>
        <Fade in={true} unmountOnExit>
          <Box
            sx={{
              height: "100vh",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Box
              sx={{
                minHeight: "64px",
                width: "100%",
                maxHeight: "64px",
                padding: "4px 0",
                backgroundColor: "primary.main",
                display: "flex",
                justifyContent: "center",
              }}
              color="primary"
            >
              <Image
                src={logo}
                alt="Logo"
                style={{
                  objectFit: "contain",
                  height: "100%",
                  marginBottom: "24px",
                }}
              />
            </Box>
            <Box
              sx={{
                flexGrow: 1,
                width: "100%",
                overflow: "hidden",
                scroll: "none",
              }}
            >
              <Box
                sx={{
                  height: "100%",
                }}
              >
                <DataProcessingForm area={area} />
                <Map onPolygonClick={onPolygonClick} />
              </Box>
            </Box>
          </Box>
        </Fade>
      </main>
    </>
  );
}
