import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import NavigationModal from "@components/compound/NavigationModal";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>SAPS | Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationModal />

      <main></main>
    </>
  );
}
