import Head from 'next/head'
import logo from "../../public/logo-abertura.svg";
import Image from "next/image";
import { Roboto } from "next/font/google";
import NavigationModal from "@components/compound/NavigationModal";
import { Box, Container, Fade } from "@mui/material";
import StyledLink from "@components/styled/StyledLink";
import LoginForm from "@components/compound/LoginForm";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>SAPS | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fade in={true} unmountOnExit>
        <Container>
          <Box
            sx={{
              height: "100vh",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <Box
              sx={{
                flexGrow: 1,
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Image
                src={logo}
                alt="Logo"
                style={{
                  objectFit: "contain",
                  width: "200px",
                  height: "min-content",
                  marginBottom: "24px",
                }}
              />
              <LoginForm />
            </Box>
            <Box
              sx={{
                display: "flex",
                width: "100%",
                gap: "24px",
                justifyContent: "center",
                padding: "12px 0",
              }}
            >
              <StyledLink href={"/SAPS_privacy_policy.pdf"} target="_blank">
                Privacy Policy
              </StyledLink>
              <StyledLink href={"/SAPS_terms_of_usage.pdf"} target="_blank">
                Terms of usage
              </StyledLink>
            </Box>
          </Box>
        </Container>
      </Fade>

      <NavigationModal />
    </>
  );
}
