import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import NavigationModal from "@components/compound/NavigationModal";
import {
  Box,
  Container,
  Fade,
  Table,
  TableBody,
  TableContainer,
  TableFooter,
  TablePagination,
  TableRow,
} from "@mui/material";
import { useState } from "react";
import TablePaginationActions from "@mui/material/TablePagination/TablePaginationActions";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin-ext"],
});

export default function Home() {
  const [page, setPage] = useState(0);

  return (
    <>
      <Head>
        <title>SAPS | Processing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationModal />

      <Fade in={true} unmountOnExit>
        <Box
          sx={{
            height: "100vh",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <Box
            sx={{
              minHeight: "64px",
              width: "100%",
              backgroundColor: "primary.main",
            }}
            color="primary"
          ></Box>
          <Box
            sx={{
              flexGrow: 1,
              width: "100%",
            }}
          >
            <Container>
              <TableContainer>
                <Table>
                  <TableBody></TableBody>
                  <TableFooter>
                    <TableRow>
                      <TablePagination
                        rowsPerPageOptions={[
                          5,
                          10,
                          25,
                          { label: "All", value: -1 },
                        ]}
                        colSpan={3}
                        count={5}
                        rowsPerPage={5}
                        page={page}
                        SelectProps={{
                          inputProps: {
                            "aria-label": "rows per page",
                          },
                          native: true,
                        }}
                        onPageChange={() => {}}
                        onRowsPerPageChange={() => {}}
                        ActionsComponent={TablePaginationActions}
                      />
                    </TableRow>
                  </TableFooter>
                </Table>
              </TableContainer>
            </Container>
          </Box>
        </Box>
      </Fade>
    </>
  );
}
